services:
  postgres:
    image: 'postgres:17.4'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/sparkplug
    ports:
      - "5402:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/sparkplug

volumes:
  postgres_data: